apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: watch-logs-pipeline
spec:
  params:
    - name: OWNER
      type: string
      description: Repository owner on which to watch the logs
    - name: REPO
      type: string
      description: Repository on which to watch the logs
    - name: WORKFLOW_ID
      type: string
      description: Id of the worflow to watch logs
    - name: TOKEN_FILE_NAME
      type: string
      description: Token file name
      default: token.txt
  tasks:
    - name: gh-logs-watcher
      params:
        - name: OWNER
          value: "$(params.OWNER)"
        - name: REPO
          value: "$(params.REPO)"
        - name: WORKFLOW_ID
          value: "$(params.WORKFLOW_ID)"
        - name: TOKEN_FILE_NAME
          value: "$(params.TOKEN_FILE_NAME)"
      taskRef:
        name: gh-logs-watcher
        bundle: quay.io/jduimovich0/watcher:2022-07-20-092404
      workspaces:
        - name: secrets
          workspace: secrets
  workspaces:
    - name: secrets
